// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSMJzrbCSKs_93ddKAsqJAo7PutzDCaGg',
    appId: '1:489974676897:web:7ab675cabd759114e5dfe0',
    messagingSenderId: '489974676897',
    projectId: 'worldcup-3b06a',
    authDomain: 'worldcup-3b06a.firebaseapp.com',
    storageBucket: 'worldcup-3b06a.firebasestorage.app',
    measurementId: 'G-QZGX2MSJKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWU4QTvwd5FWxNWTfTg0hKnrYPrc53-xs',
    appId: '1:489974676897:android:86ae99b852afa90ce5dfe0',
    messagingSenderId: '489974676897',
    projectId: 'worldcup-3b06a',
    storageBucket: 'worldcup-3b06a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaUoTmw8q7ftCl3QZXFPn7C1A5P8cBwfg',
    appId: '1:489974676897:ios:61e712b1d9909616e5dfe0',
    messagingSenderId: '489974676897',
    projectId: 'worldcup-3b06a',
    storageBucket: 'worldcup-3b06a.firebasestorage.app',
    iosBundleId: 'com.iz.worldcup2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaUoTmw8q7ftCl3QZXFPn7C1A5P8cBwfg',
    appId: '1:489974676897:ios:61e712b1d9909616e5dfe0',
    messagingSenderId: '489974676897',
    projectId: 'worldcup-3b06a',
    storageBucket: 'worldcup-3b06a.firebasestorage.app',
    iosBundleId: 'com.iz.worldcup2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSMJzrbCSKs_93ddKAsqJAo7PutzDCaGg',
    appId: '1:489974676897:web:d604bd2ad5e88724e5dfe0',
    messagingSenderId: '489974676897',
    projectId: 'worldcup-3b06a',
    authDomain: 'worldcup-3b06a.firebaseapp.com',
    storageBucket: 'worldcup-3b06a.firebasestorage.app',
    measurementId: 'G-HQMSQ4LD19',
  );
}
